import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const reactRoot = resolve(here, "..");
const projectRoot = resolve(reactRoot, "..");
const publicRoot = join(reactRoot, "public");
const legacyRoot = join(reactRoot, "public", "legacy");

const pages = ["index.html", "login.html", "chat.html", "dm.html", "news.html", "profile.html"];
const files = [
  "app.js",
  "archive.js",
  "auth.js",
  "chat.js",
  "cloudinary-config.js",
  "dm.js",
  "feed.js",
  "firebase-config.js",
  "firebase-messaging-sw.js",
  "games.js",
  "manifest.json",
  "news.js",
  "profile.js",
  "recovery.js",
  "service-worker.js",
  "style.css",
  "sw-register.js"
];

function extract(html) {
  const title = html.match(/<title>([\s\S]*?)<\/title>/i)?.[1]?.trim() || "Alfa Club";
  const bodyAttrs = html.match(/<body\b([^>]*)>/i)?.[1] || "";
  const bodyClass = bodyAttrs.match(/class=["']([^"']*)["']/i)?.[1] || "";
  const body = html
    .match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1]
    ?.replace(/<script\b[\s\S]*?<\/script>/gi, "")
    .trim() || "";

  const inlineStyles = [...html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)]
    .map((match) => match[1].trim())
    .filter(Boolean)
    .join("\n\n");

  return { title, bodyClass, inlineStyles, body };
}

function jsString(value) {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

await rm(legacyRoot, { recursive: true, force: true });
await mkdir(legacyRoot, { recursive: true });
await rm(join(publicRoot, "icons"), { recursive: true, force: true });

for (const file of files) {
  await cp(join(projectRoot, file), join(legacyRoot, file), { force: true });
}

await cp(join(projectRoot, "icons"), join(legacyRoot, "icons"), { recursive: true, force: true });
await cp(join(projectRoot, "icons"), join(publicRoot, "icons"), { recursive: true, force: true });
await cp(join(projectRoot, "manifest.json"), join(publicRoot, "manifest.json"), { force: true });
await cp(join(projectRoot, "firebase-messaging-sw.js"), join(publicRoot, "firebase-messaging-sw.js"), { force: true });
await cp(join(projectRoot, "service-worker.js"), join(publicRoot, "service-worker.js"), { force: true });

const pageData = {};
for (const page of pages) {
  pageData[page] = extract(await readFile(join(projectRoot, page), "utf8"));
}

const output = `// Generated by scripts/sync-legacy.mjs. Do not edit by hand.
export const legacyPages = ${jsString(pageData)};
`;

await writeFile(join(reactRoot, "src", "legacy-pages.generated.js"), output, "utf8");
